vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
vim.keymap.set('n', '<space>w', '<cmd>write<cr>', { desc = 'Save' })

vim.keymap.set('n', 'tt', ':NERDTreeToggle<CR>', { desc = 'Toggle File Explorer' })
vim.keymap.set('n', '<tab>', ':bnext<CR>', { desc = 'Go To the next buffer' })
vim.keymap.set('n', 'vv', ':vsp<CR>', { desc = 'Split the buffer vertically' })
vim.keymap.set('n', 'vh', ':sp<CR>', { desc = 'Split the buffer horizontally' })
vim.keymap.set('n', 'vb', ':vertical resize +10<CR>', { desc = 'resize the buffer vertically by +10' })
vim.keymap.set('n', 'vc', ':vertical resize -10<CR>', { desc = 'resize the buffer vertically by +10' })
vim.keymap.set('n', 'hj', ':resize +10<CR>', { desc = 'resize the buffer horizontally by +10' })
vim.keymap.set('n', 'hg', ':resize -10<CR>', { desc = 'resize the buffer horizontally by +10' })
vim.keymap.set('n', '<space>h', '<C-W>h')
vim.keymap.set('n', '<space>j', '<C-W>j')
vim.keymap.set('n', '<space>k', '<C-W>k')
vim.keymap.set('n', '<space>l', '<C-W>l')
vim.keymap.set('n', '<space><Left>', '<C-W>h')
vim.keymap.set('n', '<space><Down>', '<C-W>j')
vim.keymap.set('n', '<space><Up>', '<C-W>k')
vim.keymap.set('n', '<space><Right>', '<C-W>l')
vim.keymap.set('n', '<space><space>', 'i<space><Esc>')
vim.keymap.set('n', '<C-q>', ':copen<CR>')
vim.keymap.set('n', '<C-j>', ':cNext<CR>')
vim.keymap.set('n', '<C-k>', ':cprevious<CR>')
vim.keymap.set('n', '<C-c>', ':cclose<CR>')
vim.keymap.set('n', '<leader>l', ':lopen<CR>')
vim.keymap.set('n', '<leader>j', ':lNext<CR>')
vim.keymap.set('n', '<leader>k', ':lprevious<CR>')
vim.keymap.set('n', '<leader>c', ':lclose<CR>')
vim.keymap.set('n', '<leader>tt', ':TagbarToggle<CR>')
vim.keymap.set('n', '<leader>ff', '<cmd>Telescope find_files<cr>')
vim.keymap.set('n', '<leader>fg', '<cmd>Telescope live_grep<cr>')
vim.keymap.set('n', '<leader>fb', '<cmd>Telescope file_browser<cr>')
vim.keymap.set('n', '<leader>cs', '<cmd>Telescope colorscheme<cr>')
vim.keymap.set('n', '<leader>p', ':Prettier<cr>')
vim.keymap.set('n', 'n', 'nzzzv')
vim.keymap.set('n', 'N', 'Nzzzv')
vim.keymap.set('n', '<leader>w', ':w<CR>')
vim.keymap.set('n', '<C-s>', ":source ~/.config/nvim/init.lua<CR>")

vim.keymap.set('i', 'ii', '<Esc>', { desc = "Get into normal mode after pressing ii" })
vim.keymap.set('i', '<C-d>', '<Esc>ddO', { desc = "Delete the current line and go back to the deleted line number" })
